services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    volumes:
      - './config_unbound:/opt/unbound/etc/unbound/'
    networks:
      - dns
    command: ["unbound", "-d", "-c", "/opt/unbound/etc/unbound/unbound.conf"]
    healthcheck:
      test: ["CMD", "true"]

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "280:80/tcp"
    environment:
      - TZ=Europe/Moscow
      - FTLCONF_webserver_api_password=${PIHOLE_PASSWORD}
      - FTLCONF_dns_listeningMode=ALL
      - FTLCONF_dns_upstreams=unbound;8.8.8.8;1.1.1.1
    volumes:
      - './config_pihole:/etc/pihole/'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    env_file:
      - ".env"
    restart: unless-stopped
    networks:
      - dns
    depends_on:
      - unbound

  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SUBDOMAINS=${SUBDOMAIN}
      - TOKEN=${TOKEN}
      - LOG_FILE=false
    volumes:
      - './config_dns:/config/'
    env_file: ".env"
    restart: unless-stopped
    networks:
      - dns

networks:
  dns:
    driver: bridge